export const siteConfig = {
  name: "Mark Jhebryx Bergonio",
  description: "I build stuff that works smoothly and looks good—code + design all in one :)",
  url: "https://hex50x3.dev/",
  author: "Hex50x3",
  keywords: [
    "Software Engineer",
    "Software Developer",
    "Frontend Developer",
    "React",
    "ASP.NET",
    "Tailwind CSS",
    "SQL",
    "JavaScript",
    "TypeScript",
    "UI/UX Designer",
    "UI/UX Engineer",
    "UX Design",
    "User Interface Design",
    "Figma",
    "Wireframing",
    "Prototyping",
    "Manila",
    "Philippines",
    "Portfolio Website",
    "Creative Developer"
  ],
  locale: "en_US",
  publisher: "Mark Jhebryx Bergonio",
  logo: "/images/logo.png",
  ogImage: "/images/placeholder.jpg",
  sameAs: [
    "https://github.com/hex50x3",
    "https://www.figma.com/@hex50x3",
    "https://www.linkedin.com/in/hex50x3",
  ],
};